# This file is a template, and might need editing before it works on your project.
image: elixir:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - cd dashboard && mix deps.get

stages:
  - build
  - test

test:
  stage: test
  script:
    - cd dashboard && mix test


compile:
  stage: build
  script:
    - cd dashboard && mix compile --warnings-as-errors

format:
  stage: build
  script:
    - cd dashboard && mix format --check-formatted

lint:
  stage: build
  script:
    - cd dashboard && mix credo

